/**
 * `mcpcheck init` — scaffold a project's lint setup in one command.
 *
 * Writes (by default) two files:
 *   - `mcpcheck.config.json`  — a minimal config with the defaults spelled out
 *                               so users know what they can tune.
 *   - `.github/workflows/mcpcheck.yml` — a GitHub Actions workflow that runs
 *                                        mcpcheck on every PR and uploads SARIF
 *                                        to Code Scanning.
 *
 * `--config-only` and `--workflow-only` scope the writes. `--force` overwrites
 * existing files. Default behaviour refuses to overwrite and reports which
 * files were written, which were skipped, and why.
 */

import { mkdir, writeFile, access } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export interface InitOptions {
  cwd: string;
  force: boolean;
  configOnly?: boolean;
  workflowOnly?: boolean;
}

export interface InitResult {
  /** Files actually written. */
  written: string[];
  /** Files skipped because they existed and `--force` was not set. */
  skipped: string[];
}

const CONFIG_FILENAME = "mcpcheck.config.json";
const WORKFLOW_PATH = ".github/workflows/mcpcheck.yml";

const DEFAULT_CONFIG = `{
  "$schema": "https://raw.githubusercontent.com/MukundaKatta/mcpcheck/main/schema.json",
  "rules": {
    "missingTransport":      { "enabled": true,  "severity": "error"   },
    "conflictingTransport":  { "enabled": true,  "severity": "error"   },
    "invalidCommand":        { "enabled": true,  "severity": "error"   },
    "invalidArgs":           { "enabled": true,  "severity": "error"   },
    "invalidEnv":            { "enabled": true,  "severity": "error"   },
    "hardcodedSecret":       { "enabled": true,  "severity": "error"   },
    "invalidUrl":            { "enabled": true,  "severity": "error"   },
    "invalidTransport":      { "enabled": true,  "severity": "error"   },
    "unknownField":          { "enabled": true,  "severity": "warning" },
    "relativePath":          { "enabled": true,  "severity": "warning" },
    "emptyServers":          { "enabled": true,  "severity": "warning" },
    "duplicateServerName":   { "enabled": true,  "severity": "error"   },
    "unstableReference":     { "enabled": true,  "severity": "warning" },
    "dangerousCommand":      { "enabled": true,  "severity": "error"   }
  }
}
`;

const DEFAULT_WORKFLOW = `# Generated by \`mcpcheck init\`. Edit freely.
name: mcpcheck

on:
  pull_request:
    paths:
      - '**/mcp.json'
      - '**/.mcp.json'
      - '**/claude_desktop_config.json'
      - '**/.cursor/mcp.json'
      - '**/.codeium/windsurf/mcp_config.json'
      - 'mcpcheck.config.json'
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  mcpcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run mcpcheck
        uses: MukundaKatta/mcpcheck@v1
        with:
          paths: '**/mcp.json **/.mcp.json **/claude_desktop_config.json **/.cursor/mcp.json **/.codeium/windsurf/mcp_config.json'
          fail-on: error
          config: mcpcheck.config.json

      # SARIF upload is a no-op if mcpcheck found nothing; it is the mechanism
      # that puts findings into the Security tab and keeps them across pushes.
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: mcpcheck.sarif
`;

export async function runInit(opts: InitOptions): Promise<InitResult> {
  const written: string[] = [];
  const skipped: string[] = [];

  const wantConfig = !opts.workflowOnly;
  const wantWorkflow = !opts.configOnly;

  if (wantConfig) {
    const target = resolve(opts.cwd, CONFIG_FILENAME);
    if (!opts.force && (await exists(target))) {
      skipped.push(CONFIG_FILENAME);
    } else {
      await writeFile(target, DEFAULT_CONFIG, "utf8");
      written.push(CONFIG_FILENAME);
    }
  }

  if (wantWorkflow) {
    const target = resolve(opts.cwd, WORKFLOW_PATH);
    if (!opts.force && (await exists(target))) {
      skipped.push(WORKFLOW_PATH);
    } else {
      await mkdir(dirname(target), { recursive: true });
      await writeFile(target, DEFAULT_WORKFLOW, "utf8");
      written.push(WORKFLOW_PATH);
    }
  }

  return { written, skipped };
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
